### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by jasonshark** [yeoman/grunt-usemin#291]
I'm getting a jshint error when I run `grunt` from the command line.
```
Running "useminPrepare:html" (useminPrepare) task
Going through public/index.html to update the config
Looking for build script HTML comment blocks
Warning: An error occurred while processing a template (Cannot read property 'options' of undefined). Use --force to continue.

Aborted due to warnings.
```

In my gruntfile I have:
```
    useminPrepare: {
      html: '<%= yeoman.app %>/index.html',
      options: {
        dest: '<%= yeoman.dist %>'
      }
    },
```

And yeoman.dist is defined in grunt.initConfig:
```
    yeoman: {
      // configurable paths
      app: require('./bower.json').appPath || 'public',
      dist: 'dist'
    },
```

What's going on?

**Comment by divstudio** [comment]
Thx a lot @bruun !!

**Comment by Way** [comment]
Great hint @bruun ! Exatcly that's the way to find the real issue:
In my case I set a grunt.config value with `grunt.config.set` within a custom grunt task and that value caused the warning in the `template` function of `lodash.js` since it was missing. I changed that config key and everything works as expected!
Therefore the debug tip of @bruun is the way to go, the issue has really nothing to do with usemin and neither with the `grunt.config()`-call.

**Comment by singh1469** [comment]
Thanks @bruun

**Comment by plumpNation** [comment]
Thanks @crebbo, old thread I know, and worse I've already used this fix on another project :D

**Comment by blitzner** [comment]
I have a problem with this solution. One of my tasks is defined by way of template that is supposed to be valid when the task is run, but I wasn't ready for `useminPrepare` caring about its value. It's a completely different task, after all.

Something along the lines of:
```
task: 
{
src: '<%= valid.at.task.runtime.not.useminPrepare.runtime %>
},

useminPrepare: 
{
src: '<%= valid.for.useminPrepare %>'
} 
```

If this is somehow a horrible, horrible bit of code, I'd like to know why. Either way, I'd appreciate a different work-around.

**Comment by petertoi** [comment]
@bruun - excellent advice. thanks!

**Comment by originalwebgurl** [comment]
Building on @bruun's awesome suggestion, I've moved the log statement out of lodash and into grunt so it will only output if you run `grunt --verbose --debug`

Inside grunt's lib/grunt/template.js file inside `template.process = function...` just before it calls `_.template` I added this line: `grunt.verbose.debug(tmpl);`

**Comment by stephanebachelier** [comment]
It I understand this issue grunt.option is failing because of a configuration issue, thus it is not directly linked to usemin except that it fails in `usemin` with no comprehensible message ?

**Comment by stephanebachelier** [comment]
The error is not related to `grunt-usemin` but in your configuration. The error message "'An error occurred while processing a template ..." is the error throw by `grunt.template.process` [see](https://github.com/gruntjs/grunt/blob/master/lib/grunt/template.js#L90) and it is related to a configuration problem.
After digging in others issues in this repositories or in others repositories, all your use cases might faill into one of these cases:
-  a typo: using '<%' instead of '<%=', undefined value passed to the template function, using `<%= pkg.vesrion %>` instead of `<%= pkg.version %>`
- undefined value: when having the expression `<%= pkg.version %>, `pkg` might resolve to undefined (copy paste issue ?)
-  value defined at runtime: more problematic as you might think that grunt will parse and process the configuration at runtime while it's parsed when loading and configuring tasks. You might be able to use a function if supported for an option but it's not often the case.

I close this issue as it's not related to `usemin`. Feel free to open a new issue explaining your use case and if possible linking to this issue. I will add some doc about this problem.

**Comment by Rorkal** [comment]
@crebbo's advise workded for me, i was using bad reference to a variable. Now it works !

**Comment by aikrez** [comment]
Thanks @bruun
Some unused variables caused these errors

**Comment by jonscottclark** [comment]
Heaping on more thanks to @bruun
